name: RSE-UP-TEXTBOOK
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
  #  - jupyter-book
    - numpy
  #  - datascience
    - sphinx-multitoc-numbering
    - scipy
    - pytest
    - pyyaml